### ISSUE TITLE
Issues turning Battery on in non-cab trains

### ISSUE THREAD

**Issue by TiceShark** [metrostroi-repo/metrostroi_beta#48]
Not sure if it's been reported before or not but, I've been having issues with the new trains when turning them on. When using the spawner everything is fine but when manually placing the train cars I'm unable to turn the battery on in cars that don't have cabs. The switch exists but no matter what angle I toggle it from it no longer turns on. Or maybe I'm missing something, I don't know.

**Comment by pixelfelon** [comment]
I think this is definitely a bug, but here are some workarounds until it is fixed:
For 81-714 cars, you have to click the battery switch with the reverser wrench (in tools -> other).
For Ema508t cars, you have to use the battery switch head-on. That is, make sure you are level with it.

**Comment by TiceShark** [comment]
I'll try that when I get the chance (currently on the bus headed to school). Also how do you increase the max number of wagons spawned with the spawner? I've tried editing the lua file but nothing changed. And while I was spawning trains I had a bit of an issue. The third time I spawned a train the middle car' textures broke. (Was spawning it for the extra middle carraige, 81-714 LVZ. Didn't have the same issue with the MVM variant... Oh and are loopline stations being added to the announcer at some point or no?)

**Comment by pixelfelon** [comment]
https://github.com/metrostroi-repo/metrostroi_beta/issues/40#issuecomment-233070185
Sometimes the trains do that, yeah. Haven't really studied that part so not sure why.
I have no idea about the announcer. You'd have to ask the developers.

**Comment by TiceShark** [comment]
Actually I don't think it's a bug with the 81- trains, on the actual metro you need the reverser wrench (or some odds of key) to turn the cars on/off... But with the other ones idk.
Would have been nice if it was documented or something. :P

**Comment by glebqip** [comment]
@TheTiceisRight to turn battery you can use train reverser on switch in the middle of the door. If it wont work - you can press E on that switch(that can help). If it wont work too - sit in the pod(you can find it with flashlight) and turn on it as in cabin. I don't remember this.
Also i tried all for LVZ middle car fix. If you can - check a MVM middle car(5-8 respawns). Maybe i forgot place 1 of fixes to LVZ.
About loopline - our announcer man is very busy now and can't record new sounds to announcer.
About reverser wrench - IRL you enable battery with reverser wrench. Btw i add feature to enable switches in reverser wrench specialy(i can't add it to another weapons, because it can do lags or random shots\kills)
About documentation - i lazy to wrote it now :D, but in future i do a normal documentation

**Comment by ghost** [comment]
Who did you get to do the announcements?

**Comment by TiceShark** [comment]
Good job me, I forgot the close this when it was resolved XD
